name: CI

on:
    push:
    pull_request:

jobs:
    linter:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x, 14.x]
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}

          - run: rm -rf node_modules
          - run: yarn --frozen-lockfile --non-interactive
          - run: yarn lint
    tester:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x, 14.x]
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}

          - run: rm -rf node_modules
          - run: yarn --frozen-lockfile --non-interactive
          - run: yarn test:ci
